// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#pragma kernel CSInit

Texture2D<float4> InputImage;
RWStructuredBuffer<int> ResultBuffer;

[numthreads(1, 1, 1)]
void CSInit(uint3 id : SV_DispatchThreadID)
{
    ResultBuffer[0] = 0;
}

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    uint4 col = InputImage[id.xy];
 
    if(col.a < 1.0)
    {
        InterlockedAdd(ResultBuffer[0], 1);
    }
}